'use client';

import { useToast } from '@/hooks/use-toast';
import { GovernanceService } from '@/services/governanceService';
import type { Proposal } from '@/types/governance';
import { filterAndSortProposals } from '@/utils/governanceFilters';
import React, { useCallback, useEffect, useState } from 'react';

// If shadcn/ui card & tabs primitives exist, we can import them; otherwise fallback simple markup.
// Attempt import; if missing, TypeScript will surface and can be added later.
// @ts-ignore - soft import pattern; adjust to your actual component paths if different.
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
// @ts-ignore
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';

export interface GovernancePanelProps {
  projectId: string;
  initialTab?: string;
}

interface TabDef {
  id: string;
  label: string;
  description: string;
}

const tabs: TabDef[] = [
  {
    id: 'overview',
    label: 'Overview',
    description: 'High-level governance context for this project.',
  },
  {
    id: 'proposals',
    label: 'Proposals',
    description: 'Active and historical governance proposals impacting this project.',
  },
  {
    id: 'validation',
    label: 'Validation',
    description: 'Local validation, field evidence, and community attestation pipeline.',
  },
];

function Placeholder({ title, description }: { title: string; description: string }) {
  return (
    <div className='py-8 text-center space-y-2'>
      <h4 className='text-lg font-semibold opacity-80'>{title}</h4>
      <p className='text-sm text-muted-foreground max-w-md mx-auto opacity-70'>{description}</p>
      <p className='text-xs text-muted-foreground/70 italic'>(Data integration coming soon)</p>
    </div>
  );
}

export const GovernancePanel: React.FC<GovernancePanelProps> = ({
  projectId,
  initialTab = 'overview',
}) => {
  const [activeTab, setActiveTab] = useState(initialTab);
  const [proposals, setProposals] = useState<Proposal[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [voting, setVoting] = useState<Record<string, boolean>>({});
  // Filters & sorting state
  const [statusFilters, setStatusFilters] = useState<Set<Proposal['status']>>(new Set());
  const [typeFilters, setTypeFilters] = useState<Set<Proposal['type']>>(new Set());
  const [sortOption, setSortOption] = useState<'newest' | 'oldest' | 'most-votes' | 'ending-soon'>(
    'newest'
  );
  const { toast } = useToast();

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const data = await GovernanceService.getProposals(projectId);
        if (!cancelled) setProposals(data);
      } catch (e) {
        // eslint-disable-next-line no-console
        console.error('Failed to load proposals', e);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [projectId]);

  async function handleCreateMockProposal() {
    setCreating(true);
    try {
      const created = await GovernanceService.createProposal({
        title: `Auto Proposal ${proposals.length + 1}`,
        description: 'Autogenerated placeholder proposal for demo purposes.',
        type: 'project',
        votingPeriodDays: 7,
      });
      setProposals((prev) => [created, ...prev]);
      if (activeTab !== 'proposals') setActiveTab('proposals');
      toast({
        title: 'Proposal created',
        description: `"${created.title}" added.`,
      });
    } finally {
      setCreating(false);
    }
  }

  const handleVote = useCallback(
    async (proposalId: string, support: boolean) => {
      // Prevent double submit
      if (voting[proposalId]) return;
      setVoting((v) => ({ ...v, [proposalId]: true }));

      // Optimistic snapshot
      const prev = proposals;
      const optimistic = proposals.map((p) => {
        if (p.id !== proposalId) return p;
        const votesFor = p.votesFor + (support ? 1 : 0);
        const votesAgainst = p.votesAgainst + (!support ? 1 : 0);
        let status = p.status;
        if (votesFor >= 20) status = 'passed';
        else if (votesAgainst >= 10) status = 'rejected';
        return { ...p, votesFor, votesAgainst, status };
      });
      setProposals(optimistic);

      try {
        await GovernanceService.vote(proposalId, support);
        toast({
          title: support ? 'Vote cast: For' : 'Vote cast: Against',
          description: 'Your vote has been recorded.',
        });
      } catch (e) {
        // Rollback
        setProposals(prev);
        toast({
          title: 'Vote failed',
          description: 'We could not record your vote. Please retry.',
        });
      } finally {
        setVoting((v) => ({ ...v, [proposalId]: false }));
      }
    },
    [proposals, toast, voting]
  );

  const activeCount = proposals.filter((p) => p.status === 'active').length;

  // Derived filtered + sorted proposals
  const filteredProposals = React.useMemo(
    () =>
      filterAndSortProposals(proposals, {
        statusFilters,
        typeFilters,
        sort: sortOption,
      }),
    [proposals, statusFilters, typeFilters, sortOption]
  );

  function computeTimeRemaining(p: Proposal) {
    const ms = p.votingDeadline.getTime() - Date.now();
    if (ms <= 0) return 'Ended';
    const hours = Math.floor(ms / 1000 / 60 / 60);
    if (hours < 24) {
      const mins = Math.floor((ms / 1000 / 60) % 60);
      return `${hours}h ${mins}m left`;
    }
    const days = Math.floor(hours / 24);
    return `${days}d ${hours % 24}h left`;
  }

  return (
    <Card className='w-full'>
      <CardHeader>
        <CardTitle className='flex items-center justify-between w-full'>
          <span>Project Governance</span>
          <span className='text-xs font-normal text-muted-foreground'>ID: {projectId}</span>
        </CardTitle>
      </CardHeader>
      <CardContent>
        <Tabs value={activeTab} onValueChange={setActiveTab} className='w-full'>
          <TabsList className='grid w-full grid-cols-3'>
            <TabsTrigger value='overview'>Overview</TabsTrigger>
            <TabsTrigger value='proposals'>Proposals ({proposals.length})</TabsTrigger>
            <TabsTrigger value='validation'>Validation</TabsTrigger>
          </TabsList>
          <div className='flex justify-end mt-4'>
            <button
              type='button'
              onClick={handleCreateMockProposal}
              disabled={creating}
              className='text-xs px-3 py-1.5 rounded-md border bg-background hover:bg-accent transition-colors disabled:opacity-50'
            >
              {creating ? 'Creating...' : 'Create Proposal'}
            </button>
          </div>
          <TabsContent value='overview' className='mt-4'>
            {loading ? (
              <div className='py-6 text-center text-sm text-muted-foreground'>Loading...</div>
            ) : (
              <div className='grid grid-cols-2 gap-4'>
                <div className='p-4 border rounded-md text-center'>
                  <div className='text-2xl font-semibold'>{proposals.length}</div>
                  <div className='text-xs text-muted-foreground mt-1'>Total Proposals</div>
                </div>
                <div className='p-4 border rounded-md text-center'>
                  <div className='text-2xl font-semibold'>{activeCount}</div>
                  <div className='text-xs text-muted-foreground mt-1'>Active Votes</div>
                </div>
              </div>
            )}
          </TabsContent>
          <TabsContent value='proposals' className='mt-4'>
            {loading ? (
              <div className='py-6 text-center text-sm text-muted-foreground'>
                Loading proposals…
              </div>
            ) : proposals.length === 0 ? (
              <div className='py-8 text-center text-muted-foreground text-sm'>
                No proposals yet.
              </div>
            ) : (
              <>
                {/* Filter & sort controls */}
                <div className='mb-4 border rounded-md p-3 space-y-3 bg-muted/20'>
                  <div className='flex flex-wrap gap-4'>
                    <div className='space-y-1'>
                      <div className='text-[11px] font-medium uppercase tracking-wide opacity-70'>
                        Status
                      </div>
                      <div className='flex gap-2 flex-wrap'>
                        {(['active', 'pending', 'passed', 'rejected'] as Proposal['status'][]).map(
                          (s) => {
                            const active = statusFilters.has(s);
                            return (
                              <button
                                key={s}
                                type='button'
                                onClick={() =>
                                  setStatusFilters((prev) => {
                                    const next = new Set(prev);
                                    if (next.has(s)) next.delete(s);
                                    else next.add(s);
                                    return next;
                                  })
                                }
                                className={`text-[10px] px-2 py-1 rounded border transition-colors ${
                                  active
                                    ? 'bg-primary text-primary-foreground'
                                    : 'bg-background hover:bg-accent'
                                }`}
                              >
                                {s}
                              </button>
                            );
                          }
                        )}
                      </div>
                    </div>
                    <div className='space-y-1'>
                      <div className='text-[11px] font-medium uppercase tracking-wide opacity-70'>
                        Type
                      </div>
                      <div className='flex gap-2 flex-wrap'>
                        {(
                          ['project', 'governance', 'treasury', 'community'] as Proposal['type'][]
                        ).map((t) => {
                          const active = typeFilters.has(t);
                          return (
                            <button
                              key={t}
                              type='button'
                              onClick={() =>
                                setTypeFilters((prev) => {
                                  const next = new Set(prev);
                                  if (next.has(t)) next.delete(t);
                                  else next.add(t);
                                  return next;
                                })
                              }
                              className={`text-[10px] px-2 py-1 rounded border transition-colors ${
                                active
                                  ? 'bg-primary text-primary-foreground'
                                  : 'bg-background hover:bg-accent'
                              }`}
                            >
                              {t}
                            </button>
                          );
                        })}
                      </div>
                    </div>
                    <div className='space-y-1'>
                      <div className='text-[11px] font-medium uppercase tracking-wide opacity-70'>
                        Sort
                      </div>
                      <select
                        value={sortOption}
                        onChange={(e) => setSortOption(e.target.value as any)}
                        className='text-[11px] px-2 py-1 rounded border bg-background'
                      >
                        <option value='newest'>Newest</option>
                        <option value='oldest'>Oldest</option>
                        <option value='most-votes'>Most Votes</option>
                        <option value='ending-soon'>Ending Soon</option>
                      </select>
                    </div>
                  </div>
                  <div className='flex items-center justify-between text-[11px] text-muted-foreground'>
                    <span>
                      {filteredProposals.length} shown / {proposals.length} total
                    </span>
                    {(statusFilters.size > 0 || typeFilters.size > 0) && (
                      <button
                        type='button'
                        onClick={() => {
                          setStatusFilters(new Set());
                          setTypeFilters(new Set());
                        }}
                        className='underline hover:text-foreground'
                      >
                        Clear filters
                      </button>
                    )}
                  </div>
                  {(statusFilters.size > 0 || typeFilters.size > 0) && (
                    <div className='flex flex-wrap gap-2 pt-1'>
                      {Array.from(statusFilters).map((s) => (
                        <button
                          key={`sf-${s}`}
                          type='button'
                          onClick={() =>
                            setStatusFilters((prev) => {
                              const next = new Set(prev);
                              next.delete(s);
                              return next;
                            })
                          }
                          className='text-[10px] flex items-center gap-1 px-2 py-0.5 rounded-full bg-primary/10 text-primary border border-primary/30 hover:bg-primary/20'
                        >
                          {s}
                          <span className='opacity-60'>✕</span>
                        </button>
                      ))}
                      {Array.from(typeFilters).map((t) => (
                        <button
                          key={`tf-${t}`}
                          type='button'
                          onClick={() =>
                            setTypeFilters((prev) => {
                              const next = new Set(prev);
                              next.delete(t);
                              return next;
                            })
                          }
                          className='text-[10px] flex items-center gap-1 px-2 py-0.5 rounded-full bg-secondary/20 text-foreground border border-border hover:bg-secondary/30'
                        >
                          {t}
                          <span className='opacity-60'>✕</span>
                        </button>
                      ))}
                    </div>
                  )}
                  {/* Quick filter pills */}
                  <div className='flex gap-2 pt-2'>
                    <button
                      type='button'
                      onClick={() => setStatusFilters(new Set(['active']))}
                      className='text-[10px] px-2 py-1 rounded-full border bg-background hover:bg-accent'
                    >
                      Active
                    </button>
                    <button
                      type='button'
                      onClick={() => setSortOption('ending-soon')}
                      className='text-[10px] px-2 py-1 rounded-full border bg-background hover:bg-accent'
                    >
                      Ending Soon
                    </button>
                    <button
                      type='button'
                      onClick={() => setSortOption('most-votes')}
                      className='text-[10px] px-2 py-1 rounded-full border bg-background hover:bg-accent'
                    >
                      Most Votes
                    </button>
                  </div>
                </div>
                <ul className='space-y-3'>
                  {filteredProposals.map((p) => {
                    const total = p.votesFor + p.votesAgainst;
                    const forPct = total === 0 ? 0 : Math.round((p.votesFor / total) * 100);
                    const againstPct = total === 0 ? 0 : 100 - forPct;
                    const canVote = ['active', 'pending'].includes(p.status);
                    const isVoting = voting[p.id];
                    return (
                      <li
                        key={p.id}
                        data-testid='proposal-card'
                        className='p-4 border rounded-md bg-muted/30'
                      >
                        <div className='flex justify-between items-start mb-1'>
                          <h4 className='font-medium text-sm leading-snug'>{p.title}</h4>
                          <span className='text-[10px] uppercase tracking-wide px-2 py-0.5 rounded-full border bg-background'>
                            {p.status}
                          </span>
                        </div>
                        <p className='text-xs text-muted-foreground line-clamp-3'>
                          {p.description}
                        </p>
                        <div className='mt-3 space-y-1'>
                          <div className='h-2 w-full bg-border rounded overflow-hidden flex'>
                            <div
                              className='bg-green-500 transition-all'
                              style={{ width: `${forPct}%` }}
                            />
                            <div
                              className='bg-red-500 transition-all'
                              style={{ width: `${againstPct}%` }}
                            />
                          </div>
                          <div className='flex justify-between text-[10px] text-muted-foreground'>
                            <span>
                              {p.votesFor} For ({forPct}%)
                            </span>
                            <span>
                              {p.votesAgainst} Against ({againstPct}%)
                            </span>
                          </div>
                        </div>
                        <div className='mt-3 flex items-center justify-between'>
                          <div className='flex flex-col gap-1'>
                            <span className='text-[10px] text-muted-foreground'>
                              By {p.proposer}
                            </span>
                            {(['active', 'pending'] as Proposal['status'][]).includes(p.status) && (
                              <span className='text-[10px] text-muted-foreground/70'>
                                {computeTimeRemaining(p)}
                              </span>
                            )}
                          </div>
                          {canVote && (
                            <div className='flex gap-2'>
                              <button
                                type='button'
                                disabled={isVoting}
                                onClick={() => handleVote(p.id, true)}
                                className='text-[10px] px-2 py-1 rounded border bg-background hover:bg-green-500/10 hover:text-green-600 disabled:opacity-50'
                              >
                                {isVoting ? '...' : 'Approve'}
                              </button>
                              <button
                                type='button'
                                disabled={isVoting}
                                onClick={() => handleVote(p.id, false)}
                                className='text-[10px] px-2 py-1 rounded border bg-background hover:bg-red-500/10 hover:text-red-600 disabled:opacity-50'
                              >
                                {isVoting ? '...' : 'Reject'}
                              </button>
                            </div>
                          )}
                        </div>
                      </li>
                    );
                  })}
                </ul>
              </>
            )}
          </TabsContent>
          <TabsContent value='validation' className='mt-4'>
            <Placeholder
              title='Validation'
              description='Local validation, field evidence, and community attestation pipeline.'
            />
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};

export default GovernancePanel;
