name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dfinity/actions/setup-dfx@v1
      - run: pnpm install
      - run: pnpm build
      - run: dfx deploy
        env:
          DFX_PRIVATE_KEY: ${{ secrets.DFX_PRIVATE_KEY }}
