name: Dependency Security Audit

on:
  pull_request:
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
  push:
    branches: [main]
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run pnpm audit
        run: pnpm audit --audit-level=high
      - name: Upload audit report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pnpm-audit-report
          path: audit.json
        continue-on-error: true
